# Ultimate Volcano Global Setups
autoStart:
  statusCheckInterval: 144000
  probability:
    dormant:
      increase: 0.05
      decrease: 0.005
    minor_activity:
      increase: 0.1
      decrease: 0.05
    major_activity:
      increase: 0.2
      decrease: 0.1
  disallowLavaPourNonCrater: true

defaultvolcano:
  lavaflow:
    delayFlowed: 3
    flowed: 6
  autoStart:
    eruptionTimer: 6000
    pourLavaStart: true
    canAutoStart: true
  generator:
    layer: "STONE,100"
    craterRadius: 12
  erupt:
    isExplosive: true
    delayExplo: 30
    damageExplo: 20
    realDamageExplo: 2
    timerExplo: 4
    maxBombCount: 30
    minBombCount: 2
  bombs:
    maxPower: 4.0
    minPower: 2.0
    maxLaunchPower: 20.0
    minLaunchPower: 2.0
    maxRadius: 4
    minRadius: 1
    maxCalderaPower: 120.0
    minCalderaPower: 40.0
    bombDelay: 20


